source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      if config.name != "Release"
        config.build_settings['DEVELOPMENT_TEAM'] = "MXMSC4DCDK"
      else
        config.build_settings['DEVELOPMENT_TEAM'] = "44267PHH83"
      end
    end
  end
end

target 'VideoLab_Example' do
  pod 'VideoLab', :path => '../'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'SnapKit'
  pod 'PKHUD', '~> 5.0'
end
